set up cleaner makenotes for rmarkdown

diff --git a/.scripts/makenotes b/.scripts/makenotes
--- a/.scripts/makenotes
+++ b/.scripts/makenotes
@@ -1,69 +1,64 @@
 #!/bin/bash
 
-pdfreader="zathura"
+#
+# Script to compile most documents (markdown, latex etc)
+#
 
-#This script is used to compile my latex notes and open them
+usage()
+{
+    script=${0##*/}
+    echo
+    echo "Usage of ${script}: "
+    echo "----------------"
+    echo "$script <document> [to_open?]"
+    echo "Compiles document using appropriate tool"
+    echo "Also opens the output file if the to_open flag was set by typing 'o'"
+    echo "----------------"
+    echo
+    echo "Error: $1"
 
-#The name of the latex file, with respect to this file, without the .tex extension
+    exit 1
+}
+
+
 #TODO: make it so that you can run makenotes from any directory, right now it
 #      creates the new pdf in the location of execution and opens the file in the
 #      subdirectory
+# TODO: Write options for specifying output format
+# TODO: Pass additional arguments to this script to the underlying tool
 
 fullfile="$1"
-filetypeout=".pdf"
+to_open="$2"    # Whether or not output should be opened
 
-filetypein="${fullfile##*.}"
-file="${fullfile%.*}"
+filetypeout=".pdf"            # TODO: Write options for specifying output format
+filetypein="${fullfile##*.}"  # Input extension
+file="${fullfile%.*}"         # Just the filename with no extension
 
-if [ "$file" == "" ]
-then
-	echo -e "No file specified as target"
-	exit 1
+if [ "$file" == "" ] ; then
+    usage "No file specified as target"
 fi
 
-#Whether or not the file should be opened or not after compiling
-open=$2
+case "$filetypein" in
 
-if [ "$open" == "" ]
+    "tex")
+        pdflatex $file
+        ;;
+
+    "md")
+        makeprg="pandoc --pdf-engine=pdflatex -V geometry:margin=1in"
+        $makeprg $fullfile -o $file$filetypeout
+        ;;
+
+    "rmd")
+        makeprg="Rscript -e \"rmarkdown::render('$fullfile', clean=TRUE)\""
+        eval $makeprg
+        ;;
+esac
+
+if [ $? -eq 0 ] && [ "$to_open" ==  "o" ]
 then
-	open="0"
-fi
-
-if [ "$filetypein" == "tex" ]
-then
-    #The command used to make the notes
-    makefile="pdflatex"
-
-    echo "Compiling (with pdflatex)" $file".pdf from" $fullfile
-    $makefile "$file"
-fi
-
-if [ "$filetypein" == "md" ]
-then
-
-    #The command used to make the notes
-    makefile="pandoc --pdf-engine=pdflatex -V geometry:margin=1in"
-
-    echo "Compiling (with pandoc)" $file".pdf from" $fullfile
-    $makefile "$fullfile" -o "$file$filetypeout"
-fi
-
-if [ "$filetypein" == "adoc" ]
-then
-
-    #The command used to make the notes
-    makefile="asciidoctor-pdf"
-
-    echo "Compiling (with asciidoctor)" $file".pdf from" $fullfile
-    $makefile "$fullfile"
-fi
-
-
-if [ $? -eq 0 ] && [ "$open" ==  "o" ]
-then
-	echo -e "\nOpening" $file$filetypeout
-	$pdfreader "$file$filetypeout"
-elif [ "$open" != "o" ]
+	$READER "$file$filetypeout"
+elif [ "$to_open" != "o" ]
 then
 	echo -e "\nOpen-file is not set, doing nothing."
 else
@@ -71,7 +66,7 @@ else
 	read confirm
 	if [ "$confirm" == "y" ] || [ "$confirm" == "Y" ]
 	then
-		$pdfreader "$file$filetypeout"
+		$READER "$file$filetypeout"
 	fi
 fi
 
